"""LayoutLMv3 fine-tuning template for Docaro.

Supports two training sources:
1) `--layout-input`: real dataset with words/boxes/image_path generated by
   `ml/training/build_layoutlmv3_dataset.py`.
2) `--input`: fallback mode for `ground_truth.jsonl` (synthetic boxes + blank image).
"""

from __future__ import annotations

import argparse
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import torch
from PIL import Image
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from transformers import (
    LayoutLMv3ForSequenceClassification,
    LayoutLMv3Processor,
    Trainer,
    TrainingArguments,
)


LABEL_ALIASES: Dict[str, List[str]] = {
    "supplier": ["supplier", "supplier_canonical"],
    "doc_type": ["doc_type", "doctype"],
    "doc_date_iso": ["doc_date_iso", "date"],
    "doc_number": ["doc_number"],
}


@dataclass
class TextRow:
    text: str
    label: str


@dataclass
class LayoutRow:
    words: List[str]
    boxes: List[List[int]]
    image_path: Path
    label: str


def _load_rows(path: Path, label_field: str, min_text_len: int = 5) -> List[TextRow]:
    if label_field not in LABEL_ALIASES:
        valid = ", ".join(sorted(LABEL_ALIASES.keys()))
        raise ValueError(f"Unsupported label_field='{label_field}'. Valid: {valid}")

    rows: List[TextRow] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            item = json.loads(line)
        except Exception:
            continue

        labels = item.get("labels") or {}
        label_value = ""
        for key in LABEL_ALIASES[label_field]:
            value = labels.get(key)
            if value is not None and str(value).strip():
                label_value = str(value).strip()
                break
        if not label_value:
            continue

        text = str(item.get("text") or "").strip()
        if len(text) < min_text_len:
            continue
        rows.append(TextRow(text=text, label=label_value))
    return rows


def _load_layout_rows(path: Path, label_field: str, min_words: int = 4) -> List[LayoutRow]:
    rows: List[LayoutRow] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            item = json.loads(line)
        except Exception:
            continue

        words = item.get("words") or []
        boxes = item.get("boxes") or []
        image_path = item.get("image_path") or ""
        if len(words) < min_words or len(words) != len(boxes) or not image_path:
            continue

        label = str(item.get("label") or "").strip()
        if not label:
            labels = item.get("labels") or {}
            for key in LABEL_ALIASES.get(label_field, []):
                value = labels.get(key)
                if value is not None and str(value).strip():
                    label = str(value).strip()
                    break
        if not label:
            continue

        rows.append(
            LayoutRow(
                words=[str(w) for w in words],
                boxes=[[int(v) for v in b] for b in boxes],
                image_path=Path(image_path),
                label=label,
            )
        )
    return rows


def _synthetic_boxes(words: List[str]) -> List[List[int]]:
    boxes: List[List[int]] = []
    x, y = 0, 0
    token_w = 38
    token_h = 26
    max_x = 1000

    for _ in words:
        x1, y1 = x, y
        x2, y2 = min(x + token_w, 1000), min(y + token_h, 1000)
        boxes.append([x1, y1, x2, y2])
        x += token_w + 6
        if x >= max_x - token_w:
            x = 0
            y += token_h + 8
            if y >= 1000 - token_h:
                y = 0
    return boxes


def _to_features_from_text(
    texts: List[str],
    labels: List[int],
    processor: LayoutLMv3Processor,
    max_length: int,
) -> Dict[str, List]:
    blank = Image.new("RGB", (224, 224), color="white")

    all_input_ids: List[List[int]] = []
    all_attention_mask: List[List[int]] = []
    all_bbox: List[List[List[int]]] = []
    all_pixel_values: List[List[List[List[float]]]] = []
    all_labels: List[int] = []

    for text, label in zip(texts, labels):
        words = text.split()
        if not words:
            continue
        boxes = _synthetic_boxes(words)
        enc = processor(
            images=blank,
            text=words,
            boxes=boxes,
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt",
        )
        all_input_ids.append(enc["input_ids"][0].tolist())
        all_attention_mask.append(enc["attention_mask"][0].tolist())
        all_bbox.append(enc["bbox"][0].tolist())
        all_pixel_values.append(enc["pixel_values"][0].tolist())
        all_labels.append(label)

    return {
        "input_ids": all_input_ids,
        "attention_mask": all_attention_mask,
        "bbox": all_bbox,
        "pixel_values": all_pixel_values,
        "labels": all_labels,
    }


def _to_features_from_layout(
    rows: List[LayoutRow],
    label2id: Dict[str, int],
    processor: LayoutLMv3Processor,
    max_length: int,
) -> Dict[str, List]:
    all_input_ids: List[List[int]] = []
    all_attention_mask: List[List[int]] = []
    all_bbox: List[List[List[int]]] = []
    all_pixel_values: List[List[List[List[float]]]] = []
    all_labels: List[int] = []

    for row in rows:
        if row.label not in label2id:
            continue
        if not row.image_path.exists():
            continue

        image = Image.open(row.image_path).convert("RGB")
        enc = processor(
            images=image,
            text=row.words,
            boxes=row.boxes,
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt",
        )
        all_input_ids.append(enc["input_ids"][0].tolist())
        all_attention_mask.append(enc["attention_mask"][0].tolist())
        all_bbox.append(enc["bbox"][0].tolist())
        all_pixel_values.append(enc["pixel_values"][0].tolist())
        all_labels.append(label2id[row.label])

    return {
        "input_ids": all_input_ids,
        "attention_mask": all_attention_mask,
        "bbox": all_bbox,
        "pixel_values": all_pixel_values,
        "labels": all_labels,
    }


def _build_dataset(features: Dict[str, List]):
    from datasets import Dataset

    return Dataset.from_dict(features)


def _metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": float(accuracy_score(labels, preds)),
        "f1_macro": float(f1_score(labels, preds, average="macro")),
    }


def _stratified_split(y: List[int], test_size: float, seed: int):
    idx = list(range(len(y)))
    label_counts: Dict[int, int] = {}
    for yy in y:
        label_counts[yy] = label_counts.get(yy, 0) + 1
    can_stratify = len(label_counts) > 1 and min(label_counts.values()) >= 2
    stratify = y if can_stratify else None
    return train_test_split(idx, test_size=test_size, random_state=seed, stratify=stratify)


def run_training(
    input_path: Path,
    layout_input_path: Optional[Path],
    output_dir: Path,
    label_field: str,
    model_name: str,
    max_samples: int,
    max_length: int,
    test_size: float,
    seed: int,
    epochs: int,
    batch_size: int,
    learning_rate: float,
) -> Dict[str, float]:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    processor = LayoutLMv3Processor.from_pretrained(model_name, apply_ocr=False)

    labels: List[str]
    train_ds = None
    eval_ds = None

    if layout_input_path is not None:
        layout_rows = _load_layout_rows(layout_input_path, label_field=label_field)
        if max_samples > 0:
            layout_rows = layout_rows[:max_samples]
        if len(layout_rows) < 8:
            raise ValueError(f"Not enough layout rows ({len(layout_rows)}). Need >= 8.")

        labels = sorted({r.label for r in layout_rows})
        label2id = {name: i for i, name in enumerate(labels)}
        id2label = {i: name for name, i in label2id.items()}
        y = [label2id[r.label] for r in layout_rows]

        train_idx, eval_idx = _stratified_split(y, test_size=test_size, seed=seed)
        train_rows = [layout_rows[i] for i in train_idx]
        eval_rows = [layout_rows[i] for i in eval_idx]

        train_ds = _build_dataset(
            _to_features_from_layout(train_rows, label2id=label2id, processor=processor, max_length=max_length)
        )
        eval_ds = _build_dataset(
            _to_features_from_layout(eval_rows, label2id=label2id, processor=processor, max_length=max_length)
        )
    else:
        rows = _load_rows(input_path, label_field=label_field)
        if max_samples > 0:
            rows = rows[:max_samples]
        if len(rows) < 8:
            raise ValueError(f"Not enough rows for training ({len(rows)}). Need >= 8.")

        labels = sorted({r.label for r in rows})
        label2id = {name: i for i, name in enumerate(labels)}
        id2label = {i: name for name, i in label2id.items()}

        texts = [r.text for r in rows]
        y = [label2id[r.label] for r in rows]

        train_idx, eval_idx = _stratified_split(y, test_size=test_size, seed=seed)
        x_train = [texts[i] for i in train_idx]
        x_eval = [texts[i] for i in eval_idx]
        y_train = [y[i] for i in train_idx]
        y_eval = [y[i] for i in eval_idx]

        train_ds = _build_dataset(_to_features_from_text(x_train, y_train, processor, max_length=max_length))
        eval_ds = _build_dataset(_to_features_from_text(x_eval, y_eval, processor, max_length=max_length))

    model = LayoutLMv3ForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(labels),
        label2id=label2id,
        id2label=id2label,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    args = TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        learning_rate=learning_rate,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_steps=10,
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        greater_is_better=True,
        remove_unused_columns=False,
        report_to=[],
        seed=seed,
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        processing_class=processor,
        compute_metrics=_metrics,
    )
    trainer.train()
    metrics = trainer.evaluate()

    trainer.save_model(str(output_dir / "model"))
    processor.save_pretrained(str(output_dir / "model"))
    (output_dir / "label_map.json").write_text(
        json.dumps({"label2id": label2id, "id2label": id2label}, ensure_ascii=True, indent=2),
        encoding="utf-8",
    )
    (output_dir / "metrics.json").write_text(
        json.dumps(metrics, ensure_ascii=True, indent=2),
        encoding="utf-8",
    )
    return {k: float(v) for k, v in metrics.items() if isinstance(v, (int, float))}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="LayoutLMv3 fine-tuning template for Docaro")
    parser.add_argument("--input", type=Path, default=Path("data/ml/ground_truth.jsonl"))
    parser.add_argument("--layout-input", type=Path, default=None)
    parser.add_argument("--output-dir", type=Path, default=Path("artifacts/layoutlmv3/supplier"))
    parser.add_argument(
        "--label-field",
        type=str,
        default="supplier",
        choices=["supplier", "doc_type", "doc_date_iso", "doc_number"],
    )
    parser.add_argument("--model-name", type=str, default="microsoft/layoutlmv3-base")
    parser.add_argument("--max-samples", type=int, default=0)
    parser.add_argument("--max-length", type=int, default=256)
    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--learning-rate", type=float, default=2e-5)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    metrics = run_training(
        input_path=args.input,
        layout_input_path=args.layout_input,
        output_dir=args.output_dir,
        label_field=args.label_field,
        model_name=args.model_name,
        max_samples=args.max_samples,
        max_length=args.max_length,
        test_size=args.test_size,
        seed=args.seed,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
    )
    print(json.dumps(metrics, ensure_ascii=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
